# Generated by Django 3.1.4 on 2021-05-31 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
                ('email_id', models.CharField(max_length=120)),
                ('eid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('position', models.TextField()),
                ('languages', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('profile_photo', models.ImageField(upload_to='profile_pics/')),
                ('social_media', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(through='employee.Meets', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='meetings',
            field=models.ManyToManyField(through='employee.Meets', to='employee.meeting'),
        ),
    ]
