# Generated by Django 3.1.4 on 2021-06-01 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210601_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
