# Generated by Django 3.1.4 on 2021-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210601_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='email_id_of_participants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
