# Generated by Django 3.1.4 on 2021-06-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210601_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
