# Generated by Django 3.1.4 on 2021-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
